name: .NET

on:
  push:
    branches: [ staging ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.301
    - name: Build
      run: |
        ./build.sh build
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v4
      with: 
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./output