name: .NET

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.301
    - name: Install chrome
      uses: browser-actions/setup-chrome@v1
    # - name: Install chrome
    #   run: |
    #     sudo apt-get update
    #     sudo apt-get install -y wget gdebi
    #     wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
    #     sudo gdebi -n google-chrome*.deb
    - name: Build
      run: |
        ./build.sh build
        ./build.sh serve &
        sleep 10
        chrome --headless --print-to-pdf="./output/cv.pdf" http://localhost:8000 --no-pdf-header-footer --no-sandbox --disable-setuid-sandbox
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v4
      with: 
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./output